### ISSUE TITLE
How do we attach subscription model to user

### ISSUE THREAD

**Issue by johnzeus14** [kogan/django-subscriptions#13]
How do we track subscribed users with this package..is there no way to attach subscription to individual users

**Comment by jarshwah** [comment]
The subscription attachment is up to the user. We use this package in two different projects, and the model we attach the subscription object to is very different in each. 

You probably want an intermediate model, because once a subscription ends it can’t be restarted, so you’d need to create a new one. 

You also probably want to associate payment information with the subscription in some way.

**Comment by johnzeus14** [comment]
okay, do we link it up with a foreign key or a one to one field ??

**Comment by jarshwah** [comment]
It'd depend on the model you're attaching it to. I'm using OneToOneField, but the attachment can be created per-user multiple times.

**Comment by johnzeus14** [comment]
okay that is what i wanted to  understand.

so lets say my user model


class User (AbstractBaseUser):
	full_name		=	models.CharField(max_length=3000 , verbose_name = "name of individual or Company")
	email			=	models.EmailField(verbose_name = 'email address', max_length = 225, unique = True)

	account_type 	=	models.CharField(max_length = 3000 ,choices = ACCOUNT_TYPE)
	verified 		=	models.BooleanField(default = False, blank  = True)



	
	is_active		=	models.BooleanField(default = True)
	is_admin 		=	models.BooleanField(default = False)
        subscription     =     Subscription()    -------> this here right

	objects 		=   UserManager()

**Comment by jarshwah** [comment]
If you're putting the subscription directly on the User, then use a ForeignKey, otherwise you won't be able to change the subscription later.

Personally, I'd look at having a middle model:

```
class User(..):
   ...

class UserSubscription(models.Model):
    user = models.OneToOneField(User)
    subscription = models.ForeignKey(Subscription)
    ... other data as necessary

```

**Comment by johnzeus14** [comment]
okay im getting it now.. im using graphql in my django project.

**Comment by johnzeus14** [comment]
how about attaching to a userprofile model.
class Profile(models.Model):
    user             = models.OneToOneField(User)
    subscription = models.ForeignKey(Subscription)
    ... other data as necessary

**Comment by jarshwah** [comment]
I don't use UserProfile's myself, but it's the same concept, so it'd work fine.

**Comment by johnzeus14** [comment]
yeah i used user profile because the profile is already connected to the user model on a one to one relationship..Thank you sir.. God Bless.....

**Comment by johnzeus14** [comment]
you can view my project at resumelive.netlify.com
