### ISSUE TITLE
how to use with django rest framework

### ISSUE THREAD

**Issue by johnzeus14** [kogan/django-subscriptions#7]
Hello, how do i use this package with the django rest framework...i want to integrate a subscrition package into my model..to restrict people from performing a certain amount of task unless they have paid subscription...Thanks and you made a wonderful package anyway

**Comment by jarshwah** [comment]
This package is useful if you need to trigger actions based on the subscription states, where a subscription lasts for a fixed period of time.

If all you need is to manage a single state (subscribe status), then you might be better off using django-fsm directly, and skipping this package.

That said, I've specifically left out DRF integration to maintain a lower number of dependencies. Build your own DRF serialiser for whatever links to the subscription object, and include the subscription fields you're interested in.

Here's a really simple one I'm using in one of my projects:


```python
class SubscriptionSerializer(serializers.ModelSerializer):
    state = serializers.SerializerMethodField()
    start = serializers.DateTimeField()
    end = serializers.DateTimeField()

    class Meta:
        model = Subscription
        fields = ("state", "start", "end")

    def get_state(self, obj):
        return SubscriptionState(obj.state).name

```

**Comment by johnzeus14** [comment]
thank you and God bless you sir, this is wonderful

**Comment by johnzeus14** [comment]
what value should be in the obj.state.name

**Comment by jarshwah** [comment]
@johnzeus14 I'm unsure what you're asking. The `get_state` method will use the `state` property of the `subscription` instance.
